## Chapter 2: Coding out First Neurons

### Plain Python

#### A layer of Neurons


In [5]:
inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1],
					[0.5,-0.91,0.26,-0.5],
					[-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

In [6]:
# Output of current layer
layer_outputs = []
# For each neuron 
for neuron_weights, neuron_bias in zip(weights, biases):
	# Zeroed output of a given neuron
	neuron_output = 0
	for n_input, weight in zip(inputs, neuron_weights):
		neuron_output += n_input * weight
	neuron_output += neuron_bias
	layer_outputs.append(neuron_output)

In [7]:
layer_outputs

[4.8, 1.21, 2.385]

### Numpy

#### A singe Neuron

In [8]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [9]:
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


#### A layer of Neurons

In [10]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
					[0.5, -0.91, 0.26, -0.5],
					[-0.26, -0.27, 0.17, 0.87]]
bias = [2.0, 3.0, 0.5]

In [11]:
layer_outputs = np.dot(weights, inputs) + bias
print(layer_outputs)

[4.8   1.21  2.385]


#### Dot Product as matrix multiplication

In [12]:
a = [1,2,3]
b = [2,3,4]
a = np.array([a])
b = np.array([b]).T
np.dot(a,b)

array([[20]])

In [13]:
inputs = [[1.0, 2.0, 3.0, 2.5],
					[2.0, 5.0, -1.0, 2.0],
					[-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
						[0.5, -0.91, 0.26, -0.5],
						[-0.26, -0.27, 0.17, 0.87]]
biases = biases = [2.0, 3.0, 0.5]

In [14]:
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
