## Chapter 4: Acivation Functions

### ReLu Actviation Function

In [6]:
import numpy as np
import nnfs
nnfs.init()
from nnfs.datasets import  spiral_data
import matplotlib.pyplot as plt
from NNFS import Layer_Dense, Activation_ReLU, Activation_Softmax

In [7]:

inputs = [0, 2,-1,3.3, -2.7, 1.1, 2.2, -100]
output = []
for i in inputs:
	if i>0:
		output.append(i)
	else:
		output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


#### Numpy equivalent

In [8]:
outputs = np.maximum(0, inputs)
print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [ ]:
layer_outputs = [4.8, 1.21, 2.385]
E = math.e
exp_values  = []
for output in layer_outputs:
	exp_values.append(E**output)
exp_values

In [ ]:
norm_base = sum(exp_values)
norm_values = []
for value in exp_values:
	norm_values.append(value/norm_base)
print("Normalized values: ", norm_values)
print("Sum of normalized values: ", sum(norm_values))

#### Numpy equivalent

In [ ]:
exp_values = np.exp(layer_outputs)
print("Exponential values:", exp_values)

norm_values = exp_values / np.sum(exp_values)
print("Normalized values:", norm_values)
print("Sum of normalized values:", sum(norm_values))

### Numpy axis tutorial

In [30]:
layer_outputs = np.array([[4.8, 1.21, 2.385], [8.9, -1.81, 0.2], [1.41, 1.051,0.026]])

In [ ]:
print('Sum without axis:', np.sum(layer_outputs))

In [ ]:
# axis = 0
print('Sum of axis 0:', np.sum(layer_outputs, axis=0))

In [ ]:
# axis = 1
print('Sum of axis 1:', np.sum(layer_outputs, axis=1))

In [ ]:
# axis =1 keepdims=True
print('Sum of axis 1 with keepdims:', np.sum(layer_outputs, axis=1, keepdims=True))

In [13]:
X, y = spiral_data(100, 3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [14]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333412 0.3333327  0.33333313]
 [0.33333495 0.333332   0.33333302]
 [0.3333358  0.3333313  0.33333293]
 [0.33333617 0.33333114 0.3333327 ]]
