## Chapter 5: Calculating Network Error With Loss

In [3]:
import math
import numpy as np
for i in range(100, 0, -1):
	print(f"{i/100}->{math.log(i/100)}")

1.0->0.0
0.99->-0.01005033585350145
0.98->-0.020202707317519466
0.97->-0.030459207484708574
0.96->-0.040821994520255166
0.95->-0.05129329438755058
0.94->-0.06187540371808753
0.93->-0.07257069283483537
0.92->-0.08338160893905101
0.91->-0.09431067947124129
0.9->-0.10536051565782628
0.89->-0.11653381625595151
0.88->-0.12783337150988489
0.87->-0.13926206733350766
0.86->-0.15082288973458366
0.85->-0.16251892949777494
0.84->-0.1743533871447778
0.83->-0.18632957819149348
0.82->-0.19845093872383832
0.81->-0.21072103131565253
0.8->-0.2231435513142097
0.79->-0.23572233352106983
0.78->-0.2484613592984996
0.77->-0.2613647641344075
0.76->-0.2744368457017603
0.75->-0.2876820724517809
0.74->-0.3011050927839216
0.73->-0.31471074483970024
0.72->-0.3285040669720361
0.71->-0.342490308946776
0.7->-0.35667494393873245
0.69->-0.37106368139083207
0.68->-0.3856624808119846
0.67->-0.40047756659712525
0.66->-0.4155154439616658
0.65->-0.4307829160924542
0.64->-0.4462871026284195
0.63->-0.4620354595965587
0.62->-

In [15]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
														[0.1, 0.5, 0.4],
														[0.02, 0.9, 0.08]])
class_targets = np.array([0,1,1])

In [18]:
len(class_targets.shape)

1

In [19]:
print(softmax_outputs[range(len(softmax_outputs)),class_targets]) 

[0.7 0.5 0.9]


In [20]:
print(-np.log(softmax_outputs[range(len(softmax_outputs)),class_targets]))

[0.35667494 0.69314718 0.10536052]


In [21]:
neg_log = -np.log(softmax_outputs[range(len(softmax_outputs)),class_targets])
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804


In [22]:
# One hot encoded class targets
softmax_outputs = np.array([[0.7, 0.1, 0.2],
														[0.1, 0.5, 0.4],
														[0.02, 0.9, 0.08]])
class_targets = np.array([[1,0,0],
													[0,1,0],
													[0,1,0]])	

In [24]:
softmax_outputs * class_targets

array([[0.7, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0.9, 0. ]])

In [23]:
len(class_targets.shape)

2

In [25]:
if len(class_targets.shape) == 1:
	correct_confidences = softmax_outputs[range(len(softmax_outputs)),class_targets]
elif len(class_targets.shape) == 2:
		correct_confidences = np.sum(softmax_outputs * class_targets, axis=1)
neg_log = -np.log(correct_confidences)
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804


In [26]:
from NNFS import Loss_CategoricalCrossentropy

In [27]:
loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(softmax_outputs, class_targets)
print(loss)

0.38506088005216804


In [29]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
from NNFS import Layer_Dense, Activation_ReLU, Activation_Softmax,Loss_CategoricalCrossentropy


In [30]:
X, y = spiral_data(100, 3)
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()
loss_function =  Loss_CategoricalCrossentropy()


In [31]:
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])
loss = loss_function.calculate(activation2.output, y)
print(loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
1.0986104


In [32]:
predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
	y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)
print(accuracy)

0.34
